[package]
name = "rust-shortener-cqrs"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.8.7"
http-body-util = "0.1.3"
nanoid = "0.4.0"
tokio = { version = "1.48.0", features = ["full"] }
tower = "0.5.2"
